-- public.alerts definition

-- Drop table

-- DROP TABLE public.alerts;

CREATE TABLE public.alerts (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz DEFAULT now() NULL,
	profile_id uuid NOT NULL,
	dev_eui text NOT NULL,
	value float8 NOT NULL,
	"name" text NOT NULL,
	"source" text NOT NULL,
	"action" text NOT NULL,
	CONSTRAINT alerts_pkey PRIMARY KEY (id)
);


-- public.cw_device_type definition

-- Drop table

-- DROP TABLE public.cw_device_type;

CREATE TABLE public.cw_device_type (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	"name" text NOT NULL,
	model text NULL,
	decoder text NULL,
	manufacturer text NULL,
	data_table text NULL,
	device_app text NULL,
	primary_data text NULL,
	primary_data_notation text NULL,
	CONSTRAINT cw_device_type_name_key UNIQUE (name),
	CONSTRAINT cw_device_type_pkey PRIMARY KEY (id)
);


-- public.cw_gps_uplinks definition

-- Drop table

-- DROP TABLE public.cw_gps_uplinks;

CREATE TABLE public.cw_gps_uplinks (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	dev_eui varchar NOT NULL,
	latitude numeric NOT NULL,
	longitude numeric NOT NULL,
	"geoPos" extensions.geometry NULL,
	"isHistoric" bool DEFAULT false NOT NULL,
	altitude numeric NULL,
	hdop numeric NULL,
	battery numeric NULL,
	collected_time timestamptz NULL,
	CONSTRAINT cw_gps_uplinks_pkey PRIMARY KEY (id)
);


-- public.cw_locations definition

-- Drop table

-- DROP TABLE public.cw_locations;

CREATE TABLE public.cw_locations (
	location_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NOT NULL,
	latitude numeric(9, 6) NULL,
	longitude numeric(9, 6) NULL,
	description text NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	CONSTRAINT cw_locations_pkey PRIMARY KEY (location_id)
);


-- public.cw_netvox_r313_uplinks definition

-- Drop table

-- DROP TABLE public.cw_netvox_r313_uplinks;

CREATE TABLE public.cw_netvox_r313_uplinks (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	dev_eui varchar NOT NULL,
	battery numeric NOT NULL,
	"deviceType" numeric NOT NULL,
	"reportType" numeric NOT NULL,
	status1 numeric NOT NULL,
	status2 numeric NOT NULL,
	is_simulation bool DEFAULT false NULL,
	"version" numeric NULL,
	CONSTRAINT cw_netvox_r313_uplinks_pkey PRIMARY KEY (id)
);


-- public.cw_vs_350_uplinks definition

-- Drop table

-- DROP TABLE public.cw_vs_350_uplinks;

CREATE TABLE public.cw_vs_350_uplinks (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	battery numeric NULL,
	total_in numeric NOT NULL,
	total_out numeric NOT NULL,
	period_in numeric NOT NULL,
	period_out numeric NOT NULL,
	historic_datetime timetz NULL,
	dev_eui varchar NOT NULL,
	CONSTRAINT cw_vs_350_pkey PRIMARY KEY (id)
);


-- public.device_data_metadata definition

-- Drop table

-- DROP TABLE public.device_data_metadata;

CREATE TABLE public.device_data_metadata (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz DEFAULT now() NULL,
	dev_eui text NOT NULL,
	data_key text NOT NULL,
	data_type text NOT NULL,
	display_as text NOT NULL,
	alias text NULL,
	divisor numeric NULL,
	CONSTRAINT device_data_metadata_pkey PRIMARY KEY (id)
);


-- public.locations definition

-- Drop table

-- DROP TABLE public.locations;

CREATE TABLE public.locations (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz DEFAULT now() NULL,
	lat numeric NULL,
	lng numeric NULL,
	"name" text NOT NULL,
	description text NULL,
	sensor_type text NULL,
	profile_id uuid NULL,
	dev_eui text NULL,
	CONSTRAINT locations_pkey PRIMARY KEY (id)
);


-- public.road_event_lines definition

-- Drop table

-- DROP TABLE public.road_event_lines;

CREATE TABLE public.road_event_lines (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz DEFAULT now() NULL,
	line_name text NOT NULL,
	camera_name text NOT NULL,
	camera_id text DEFAULT ''::text NOT NULL,
	CONSTRAINT road_event_lines_pkey PRIMARY KEY (id)
);


-- public.road_events definition

-- Drop table

-- DROP TABLE public.road_events;

CREATE TABLE public.road_events (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz DEFAULT now() NULL,
	"class" text NOT NULL,
	track_id numeric NOT NULL,
	direction numeric NOT NULL,
	source_datetime timestamptz NULL,
	server_event_datetime timestamptz DEFAULT now() NULL,
	camera_id text NULL,
	line_id text NULL,
	CONSTRAINT road_event_pkey PRIMARY KEY (id)
);


-- public.roles definition

-- Drop table

-- DROP TABLE public.roles;

CREATE TABLE public.roles (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz DEFAULT now() NULL,
	"name" text NOT NULL,
	code int8 NULL,
	description text NULL,
	CONSTRAINT roles_pkey PRIMARY KEY (id)
);


-- public.cw_devices definition

-- Drop table

-- DROP TABLE public.cw_devices;

CREATE TABLE public.cw_devices (
	dev_eui varchar(255) NOT NULL,
	"name" text DEFAULT 'UnNamed Device'::text NOT NULL,
	"type" int8 NULL,
	upload_interval numeric DEFAULT '-1'::numeric NULL,
	lat numeric NULL,
	long numeric NULL,
	installed_at date NULL,
	battery_changed_at date NULL,
	CONSTRAINT pk_cw_devices PRIMARY KEY (dev_eui),
	CONSTRAINT cw_devices_type_fkey FOREIGN KEY ("type") REFERENCES public.cw_device_type(id)
);


-- public.cw_pulse_meters definition

-- Drop table

-- DROP TABLE public.cw_pulse_meters;

CREATE TABLE public.cw_pulse_meters (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	count numeric DEFAULT '0'::numeric NOT NULL,
	dev_eui varchar NOT NULL,
	"periodCount" numeric DEFAULT '0'::numeric NOT NULL,
	"litersPerPulse" numeric DEFAULT '10'::numeric NOT NULL,
	CONSTRAINT cw_pulse_meters_pkey PRIMARY KEY (id),
	CONSTRAINT public_cw_pulse_meters_dev_eui_fkey FOREIGN KEY (dev_eui) REFERENCES public.cw_devices(dev_eui)
);


-- public.cw_soil_uplinks definition

-- Drop table

-- DROP TABLE public.cw_soil_uplinks;

CREATE TABLE public.cw_soil_uplinks (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	dev_eui varchar NULL,
	battery int4 NULL,
	temperature numeric NOT NULL,
	moisture numeric NOT NULL,
	ec numeric NULL,
	ph numeric NULL,
	n numeric NULL,
	p numeric NULL,
	k numeric NULL,
	internal_temp numeric NULL,
	real_duration numeric NULL,
	read_attempts int4 NULL,
	CONSTRAINT cw_soil_uplinks_pkey PRIMARY KEY (id),
	CONSTRAINT cw_soil_uplinks_dev_eui_fkey FOREIGN KEY (dev_eui) REFERENCES public.cw_devices(dev_eui)
);


-- public.cw_ss_tme definition

-- Drop table

-- DROP TABLE public.cw_ss_tme;

CREATE TABLE public.cw_ss_tme (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	"soil_EC" numeric NULL,
	soil_moisture numeric NOT NULL,
	"soil_temperatureC" numeric NOT NULL,
	dev_eui varchar NOT NULL,
	"modbusAttempts" int2 NULL,
	"internalTemp" numeric NULL,
	"batteryVoltage" numeric NULL,
	CONSTRAINT cw_ss_tme_pkey PRIMARY KEY (id),
	CONSTRAINT public_cw_ss_tme_dev_eui_fkey FOREIGN KEY (dev_eui) REFERENCES public.cw_devices(dev_eui)
);


-- public.cw_ss_tmepnpk definition

-- Drop table

-- DROP TABLE public.cw_ss_tmepnpk;

CREATE TABLE public.cw_ss_tmepnpk (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	"soil_EC" numeric NULL,
	soil_moisture numeric NOT NULL,
	"soil_temperatureC" numeric NOT NULL,
	"soil_PH" numeric NULL,
	dev_eui varchar NOT NULL,
	"soil_N" numeric NULL,
	"soil_P" numeric NULL,
	"soil_K" numeric NULL,
	"modbusAttempts" int2 NULL,
	"internalTemp" numeric NULL,
	"batteryVoltage" numeric NULL,
	CONSTRAINT cw_ss_tmepnpk_pkey PRIMARY KEY (id),
	CONSTRAINT cw_ss_tmepnpk_dev_eui_fkey FOREIGN KEY (dev_eui) REFERENCES public.cw_devices(dev_eui)
);


-- public.cw_watermeter_uplinks definition

-- Drop table

-- DROP TABLE public.cw_watermeter_uplinks;

CREATE TABLE public.cw_watermeter_uplinks (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	dev_eui varchar NOT NULL,
	count int8 NOT NULL,
	internal_temp float4 NULL,
	battery_level int2 NULL,
	CONSTRAINT cw_water_meter_pkey PRIMARY KEY (id),
	CONSTRAINT cw_watermeter_uplinks_dev_eui_fkey FOREIGN KEY (dev_eui) REFERENCES public.cw_devices(dev_eui)
);


-- public.cw_weather_station_uplinks definition

-- Drop table

-- DROP TABLE public.cw_weather_station_uplinks;

CREATE TABLE public.cw_weather_station_uplinks (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	dev_eui varchar NULL,
	battery int4 NULL,
	temperature numeric NOT NULL,
	humidity numeric NOT NULL,
	co2_level numeric NULL,
	pressure numeric NULL,
	CONSTRAINT cw_weather_station_uplinks_pkey PRIMARY KEY (id),
	CONSTRAINT cw_weather_station_uplinks_dev_eui_fkey FOREIGN KEY (dev_eui) REFERENCES public.cw_devices(dev_eui)
);


-- public.seeed_co2_lorawan_uplinks definition

-- Drop table

-- DROP TABLE public.seeed_co2_lorawan_uplinks;

CREATE TABLE public.seeed_co2_lorawan_uplinks (
	id serial4 NOT NULL,
	dev_eui varchar(255) NOT NULL,
	"valid" bool NULL,
	err int4 NULL,
	payload text NULL,
	rssi int4 NULL,
	snr float8 NULL,
	created_at timestamptz DEFAULT now() NULL,
	battery int4 NULL,
	"interval" int4 NULL,
	temperature float8 NULL,
	humidity float8 NULL,
	co2_level int4 NULL,
	pressure float8 NULL,
	CONSTRAINT seeed_co2_lorawan_uplinks_pkey PRIMARY KEY (id),
	CONSTRAINT public_seeed_co2_lorawan_uplinks_dev_eui_fkey FOREIGN KEY (dev_eui) REFERENCES public.cw_devices(dev_eui)
);


-- public.cw_air_thvd definition

-- Drop table

-- DROP TABLE public.cw_air_thvd;

CREATE TABLE public.cw_air_thvd (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	"dewPointC" numeric NULL,
	humidity numeric NOT NULL,
	"temperatureC" numeric NOT NULL,
	vpd numeric NULL,
	dev_eui varchar NOT NULL,
	CONSTRAINT cw_air_thvd_pkey PRIMARY KEY (id),
	CONSTRAINT cw_air_thvd_dev_eui_fkey FOREIGN KEY (dev_eui) REFERENCES public.cw_devices(dev_eui)
);


-- public.cw_co2_uplinks definition

-- Drop table

-- DROP TABLE public.cw_co2_uplinks;

CREATE TABLE public.cw_co2_uplinks (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	dev_eui varchar NULL,
	battery int4 NULL,
	temperature numeric NOT NULL,
	humidity numeric NOT NULL,
	co2_level numeric NULL,
	pressure numeric NULL,
	CONSTRAINT cw_co2_uplinks_pkey PRIMARY KEY (id),
	CONSTRAINT cw_co2_uplinks_dev_eui_fkey FOREIGN KEY (dev_eui) REFERENCES public.cw_devices(dev_eui)
);


-- public.cw_device_locations definition

-- Drop table

-- DROP TABLE public.cw_device_locations;

CREATE TABLE public.cw_device_locations (
	dev_eui varchar(255) NOT NULL,
	location_id int8 NOT NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	CONSTRAINT cw_device_locations_dev_eui_key UNIQUE (dev_eui),
	CONSTRAINT cw_device_locations_pkey PRIMARY KEY (id),
	CONSTRAINT cw_device_locations_dev_eui_fkey FOREIGN KEY (dev_eui) REFERENCES public.cw_devices(dev_eui) ON DELETE RESTRICT,
	CONSTRAINT cw_device_locations_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.cw_locations(location_id)
);


-- public.cropwatch_uplinks definition

-- Drop table

-- DROP TABLE public.cropwatch_uplinks;

CREATE TABLE public.cropwatch_uplinks (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz DEFAULT now() NULL,
	dev_eui text NULL,
	f_port int8 NULL,
	f_cnt int8 DEFAULT '0'::bigint NOT NULL,
	frm_payload text NULL,
	decoded_payload jsonb NULL,
	metadata jsonb NULL,
	confirmed bool NULL,
	received_at timestamptz DEFAULT (now() AT TIME ZONE 'utc'::text) NULL,
	ui_metadata json NULL,
	CONSTRAINT cropwatch_uplinks_pkey PRIMARY KEY (id)
);


-- public.cw_alerts definition

-- Drop table

-- DROP TABLE public.cw_alerts;

CREATE TABLE public.cw_alerts (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	dev_eui varchar NOT NULL,
	profile_id uuid NOT NULL,
	subject text NOT NULL,
	threshold_value numeric NOT NULL,
	reset_value numeric NULL,
	"operator" text NOT NULL,
	"action" text NOT NULL,
	"isTriggered" bool DEFAULT false NOT NULL,
	last_triggered date NULL,
	"name" text NOT NULL,
	action_recipient text NOT NULL,
	CONSTRAINT cw_alerts_pkey PRIMARY KEY (id)
);


-- public.cw_co2_alerts definition

-- Drop table

-- DROP TABLE public.cw_co2_alerts;

CREATE TABLE public.cw_co2_alerts (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	profile_id uuid NOT NULL,
	dev_eui varchar NOT NULL,
	"operator" text NOT NULL,
	"action" text NOT NULL,
	subject text NOT NULL,
	receiver text NOT NULL,
	cleared bool NOT NULL,
	value numeric NOT NULL,
	"OneSignalID" text NULL,
	CONSTRAINT cw_co2_alerts_pkey PRIMARY KEY (id)
);


-- public.cw_device_owners definition

-- Drop table

-- DROP TABLE public.cw_device_owners;

CREATE TABLE public.cw_device_owners (
	user_id uuid NOT NULL,
	dev_eui varchar(255) NOT NULL,
	owner_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	permission_level numeric DEFAULT '1'::numeric NOT NULL,
	CONSTRAINT cw_device_owners_owner_id_key UNIQUE (owner_id),
	CONSTRAINT cw_device_owners_pkey PRIMARY KEY (id)
);


-- public.cw_location_owners definition

-- Drop table

-- DROP TABLE public.cw_location_owners;

CREATE TABLE public.cw_location_owners (
	user_id uuid NOT NULL,
	owner_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	location_id int8 NOT NULL,
	permission_level numeric DEFAULT '1'::numeric NULL,
	is_active bool NULL,
	description text NULL,
	CONSTRAINT cw_location_owners_owner_id_key UNIQUE (owner_id),
	CONSTRAINT cw_location_owners_pkey PRIMARY KEY (id)
);


-- public.device_x_user definition

-- Drop table

-- DROP TABLE public.device_x_user;

CREATE TABLE public.device_x_user (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	dev_eui text NOT NULL,
	email varchar NOT NULL,
	profile_id uuid NULL,
	shared_name text DEFAULT 'Device Shared WIth you'::text NULL,
	CONSTRAINT device_x_user_pkey PRIMARY KEY (id)
);


-- public.devices definition

-- Drop table

-- DROP TABLE public.devices;

CREATE TABLE public.devices (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz DEFAULT now() NULL,
	dev_eui text NOT NULL,
	profile_id uuid NULL,
	"type" text DEFAULT 'Not Set'::text NULL,
	lat float8 NULL,
	lng float8 NULL,
	device_name text NULL,
	active bool DEFAULT false NOT NULL,
	linked_device_eui text NULL,
	CONSTRAINT devices_dev_eui_key UNIQUE (dev_eui),
	CONSTRAINT devices_pkey PRIMARY KEY (id)
);


-- public.location_permissions definition

-- Drop table

-- DROP TABLE public.location_permissions;

CREATE TABLE public.location_permissions (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz DEFAULT now() NULL,
	role_name int8 NOT NULL,
	expires_on timestamptz NULL,
	location_id int8 NOT NULL,
	granted_to uuid NULL,
	CONSTRAINT location_permissions_pkey PRIMARY KEY (id)
);


-- public.locations_x_devices definition

-- Drop table

-- DROP TABLE public.locations_x_devices;

CREATE TABLE public.locations_x_devices (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz DEFAULT now() NULL,
	device_id int8 NOT NULL,
	location_id int8 NOT NULL,
	CONSTRAINT locations_x_devices_pkey PRIMARY KEY (id)
);


-- public.lorawan_uplinks definition

-- Drop table

-- DROP TABLE public.lorawan_uplinks;

CREATE TABLE public.lorawan_uplinks (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz DEFAULT now() NULL,
	dev_eui text NOT NULL,
	f_port int8 NULL,
	f_cnt int8 DEFAULT '0'::bigint NOT NULL,
	frm_payload text NULL,
	decoded_payload jsonb NULL,
	metadata jsonb NULL,
	confirmed bool NULL,
	received_at timestamptz DEFAULT (now() AT TIME ZONE 'utc'::text) NULL,
	ui_metadata json NULL,
	CONSTRAINT lorawan_uplinks_pkey PRIMARY KEY (id)
);


-- public.lorawatch_uplinks definition

-- Drop table

-- DROP TABLE public.lorawatch_uplinks;

CREATE TABLE public.lorawatch_uplinks (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz DEFAULT now() NULL,
	dev_eui text NOT NULL,
	f_port int8 NULL,
	f_cnt int8 DEFAULT '0'::bigint NOT NULL,
	frm_payload text NULL,
	decoded_payload jsonb NULL,
	metadata jsonb NULL,
	confirmed bool NULL,
	received_at timestamptz DEFAULT (now() AT TIME ZONE 'utc'::text) NULL,
	ui_metadata json NULL,
	CONSTRAINT lorawatch_uplinks_pkey PRIMARY KEY (id)
);


-- public.permissions definition

-- Drop table

-- DROP TABLE public.permissions;

CREATE TABLE public.permissions (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz DEFAULT now() NULL,
	resource text NOT NULL,
	role_id int8 NOT NULL,
	allowed_profile_id uuid NULL,
	allowed_by_profile_id uuid NULL,
	description text NULL,
	CONSTRAINT permissions_pkey PRIMARY KEY (id)
);


-- public.profiles definition

-- Drop table

-- DROP TABLE public.profiles;

CREATE TABLE public.profiles (
	id uuid NOT NULL,
	updated_at timestamptz NULL,
	username text NULL,
	full_name text NULL,
	avatar_url text NULL,
	website text NULL,
	email varchar NULL,
	CONSTRAINT profiles_email_key UNIQUE (email),
	CONSTRAINT profiles_pkey PRIMARY KEY (id),
	CONSTRAINT profiles_username_key UNIQUE (username),
	CONSTRAINT username_length CHECK ((char_length(username) >= 3))
);

-- Table Triggers

create trigger before_profile_changes before
delete
    or
update
    of avatar_url on
    public.profiles for each row execute function delete_old_avatar();


-- public.role_permissions definition

-- Drop table

-- DROP TABLE public.role_permissions;

CREATE TABLE public.role_permissions (
	id serial4 NOT NULL,
	role_id int8 NULL,
	permission_id int8 NULL,
	CONSTRAINT role_permissions_pkey PRIMARY KEY (id),
	CONSTRAINT role_permissions_role_id_permission_id_key UNIQUE (role_id, permission_id)
);


-- public.sensors definition

-- Drop table

-- DROP TABLE public.sensors;

CREATE TABLE public.sensors (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	connected_device text NULL,
	lat numeric NULL,
	lng numeric NULL,
	"type" text NULL,
	address numeric NULL,
	CONSTRAINT sensors_pkey PRIMARY KEY (id)
);


-- public.temp_humid_co2_alert_settings definition

-- Drop table

-- DROP TABLE public.temp_humid_co2_alert_settings;

CREATE TABLE public.temp_humid_co2_alert_settings (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	profile_id uuid NOT NULL,
	dev_eui text NOT NULL,
	"operator" text NOT NULL,
	"action" numeric NOT NULL,
	subject text NOT NULL,
	receiver text NOT NULL,
	cleared bool NOT NULL,
	value numeric NOT NULL,
	"OneSignalID" text NULL,
	CONSTRAINT temp_humid_co2_alert_settings_pkey PRIMARY KEY (id)
);


-- public.cropwatch_uplinks foreign keys

ALTER TABLE public.cropwatch_uplinks ADD CONSTRAINT cropwatch_uplinks_dev_eui_fkey FOREIGN KEY (dev_eui) REFERENCES public.devices(dev_eui);


-- public.cw_alerts foreign keys

ALTER TABLE public.cw_alerts ADD CONSTRAINT public_cw_alerts_dev_eui_fkey FOREIGN KEY (dev_eui) REFERENCES public.cw_devices(dev_eui);
ALTER TABLE public.cw_alerts ADD CONSTRAINT public_cw_alerts_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id);


-- public.cw_co2_alerts foreign keys

ALTER TABLE public.cw_co2_alerts ADD CONSTRAINT cw_co2_alerts_dev_eui_fkey FOREIGN KEY (dev_eui) REFERENCES public.cw_devices(dev_eui);
ALTER TABLE public.cw_co2_alerts ADD CONSTRAINT cw_co2_alerts_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id);


-- public.cw_device_owners foreign keys

ALTER TABLE public.cw_device_owners ADD CONSTRAINT cw_device_owners_dev_eui_fkey FOREIGN KEY (dev_eui) REFERENCES public.cw_devices(dev_eui) ON DELETE RESTRICT;
ALTER TABLE public.cw_device_owners ADD CONSTRAINT cw_device_owners_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id);


-- public.cw_location_owners foreign keys

ALTER TABLE public.cw_location_owners ADD CONSTRAINT cw_location_owners_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.cw_locations(location_id);
ALTER TABLE public.cw_location_owners ADD CONSTRAINT cw_location_owners_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id);


-- public.device_x_user foreign keys

ALTER TABLE public.device_x_user ADD CONSTRAINT device_x_user_dev_eui_fkey FOREIGN KEY (dev_eui) REFERENCES public.devices(dev_eui);
ALTER TABLE public.device_x_user ADD CONSTRAINT device_x_user_email_fkey FOREIGN KEY (email) REFERENCES public.profiles(email);
ALTER TABLE public.device_x_user ADD CONSTRAINT device_x_user_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id);


-- public.devices foreign keys

ALTER TABLE public.devices ADD CONSTRAINT devices_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES auth.users(id);


-- public.location_permissions foreign keys

ALTER TABLE public.location_permissions ADD CONSTRAINT location_permissions_granted_to_fkey FOREIGN KEY (granted_to) REFERENCES public.profiles(id) ON DELETE CASCADE;
ALTER TABLE public.location_permissions ADD CONSTRAINT location_permissions_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id) ON DELETE CASCADE;
ALTER TABLE public.location_permissions ADD CONSTRAINT location_permissions_role_name_fkey FOREIGN KEY (role_name) REFERENCES public.roles(id);


-- public.locations_x_devices foreign keys

ALTER TABLE public.locations_x_devices ADD CONSTRAINT locations_x_devices_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.devices(id) ON DELETE CASCADE;
ALTER TABLE public.locations_x_devices ADD CONSTRAINT locations_x_devices_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id);


-- public.lorawan_uplinks foreign keys

ALTER TABLE public.lorawan_uplinks ADD CONSTRAINT lorawan_uplinks_dev_eui_fkey FOREIGN KEY (dev_eui) REFERENCES public.devices(dev_eui);


-- public.lorawatch_uplinks foreign keys

ALTER TABLE public.lorawatch_uplinks ADD CONSTRAINT lorawatch_uplinks_dev_eui_fkey FOREIGN KEY (dev_eui) REFERENCES public.devices(dev_eui);


-- public.permissions foreign keys

ALTER TABLE public.permissions ADD CONSTRAINT permissions_allowed_by_profile_id_fkey FOREIGN KEY (allowed_by_profile_id) REFERENCES public.profiles(id) ON DELETE CASCADE;
ALTER TABLE public.permissions ADD CONSTRAINT permissions_allowed_profile_id_fkey FOREIGN KEY (allowed_profile_id) REFERENCES public.profiles(id) ON DELETE CASCADE;
ALTER TABLE public.permissions ADD CONSTRAINT permissions_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id);


-- public.profiles foreign keys

ALTER TABLE public.profiles ADD CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;


-- public.role_permissions foreign keys

ALTER TABLE public.role_permissions ADD CONSTRAINT role_permissions_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES public.permissions(id);
ALTER TABLE public.role_permissions ADD CONSTRAINT role_permissions_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id);


-- public.sensors foreign keys

ALTER TABLE public.sensors ADD CONSTRAINT sensors_connected_device_fkey FOREIGN KEY (connected_device) REFERENCES public.devices(dev_eui);


-- public.temp_humid_co2_alert_settings foreign keys

ALTER TABLE public.temp_humid_co2_alert_settings ADD CONSTRAINT temp_humid_co2_alert_settings_dev_eui_fkey FOREIGN KEY (dev_eui) REFERENCES public.devices(dev_eui);
ALTER TABLE public.temp_humid_co2_alert_settings ADD CONSTRAINT temp_humid_co2_alert_settings_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id);