export const nameToEmoji = (name: string) => {
    switch (name) {
        case 'soil_moisture':
        case 'moisture':
        case 'soil_humidity':
            return '💧';
        case 'humidity':
            return '💨';
        case 'dew_point':
        case 'dew_pointC':
        case 'dewPointC':
            return '💦';
        case 'temperature':
        case 'temperatureC':
        case 'soil_temperatureC':
        case 'temperature_c':
        case 'soil_temperature':
            return '🌡️';
        case 'soil_EC':
        case 'soil_ec':
        case 'ec':
            return '🧂';
        case 'soil_N':
        case 'soil_P':
        case 'soil_K':
        case 'soil_n':
        case 'soil_p':
        case 'soil_k':
            return '🧪';
        case 'soil_PH':
        case 'soil_ph':
        case 'ph':
            return '⚗️';
        case 'co2_level':
        case 'co2':
            return '⌬';
        case 'vpd':
            return '💦';
        case 'rainfall':
            return '🌧️';
        case 'pressure':
            return '🕕';
        case 'created_at':
            return '⌛';
        case 'wind_speed':
            return '🍃';
        case 'lux':
            return '☀️';
        case 'uv':
            return '☢️';
        case 'wind_direction':
            return '🧭';
        case 'water_level':
            return '📏';
        case 'battery_level':
        case 'battery':
        case 'Battery':
            return '🔋';
        case 'sos':
            return '🆘';
        case 'fire':
            return '🔥';
        case 'people_count':
            return '🧍';
        case 'car_count':
            return '🚗';
        case 'bicycle_count':
            return '🚲';
        default:
            return '';
    }
}