export const nameToNotation = (name: string) => {
	switch (name) {
		case 'humidity':
		case 'moisture':
		case 'soil_moisture':
			return '%';
		case 'Temperature':
		case 'temperature':
		case 'temperatureC':
		case 'temperature_c':
		case 'dew_point':
		case 'dew_pointC':
		case 'dewPointC':
			return '°C';
		case 'soil_EC':
			return 'mS/m';
		case 'soil_N':
			return 'mg/kg';
		case 'soil_P':
			return 'mg/kg';
		case 'soil_K':
			return 'mg/kg';
		case 'soil_PH':
		case 'ph':
			return 'pH';
		case 'co2_level':
		case 'co2':
			return 'ppm';
		case 'vpd':
			return 'hPk';
		case 'rainfall':
			return 'mm/hr';
		case 'pressure':
			return 'hPa';
		case 'wind_speed':
			return 'm/s';
		case 'lux':
			return 'lux';
		case 'uv':
		case 'uv_index':
			return 'UVI';
		case 'soil_temperature':
		case 'soil_temperatureC':
			return '°C';
		case 'soil_humidity':
			return '%';
		case 'soil_ec':
		case 'ec':
			return 'mS/cm';
		case 'soil_ph':
			return 'pH';
		case 'soil_nitrogen':
		case 'soil_n':
			return 'mg/kg';
		case 'soil_phosphorus':
		case 'soil_p':
			return 'mg/kg';
		case 'soil_potassium':
		case 'soil_k':
			return 'mg/kg';
		case 'wind_direction':
			return '°';
		case 'water_level':
			return 'm';
		case 'battery_level':
		case 'battery':
		case 'Battery':
			return '%';
		case 'sos':
			return 'SOS';
		case 'people_count':
			return '';
		case 'car_count':
			return '';
		case 'bicycle_count':
			return '';
		case 'truck_count':
			return '';
		case 'bus_count':
			return '';
		case 'motorcycle_count':
			return '';
		case 'depth_cm':
		case 'deapth_cm':
			return 'cm';
		case 'created_at':
			return 'Last Updated';
		default:
			return '';
	}
};
