import { error, redirect, type RequestHandler } from "@sveltejs/kit";
import PdfPrinter from 'pdfmake';
import pdfFonts from 'pdfmake/build/vfs_fonts';
import QuickChart from 'quickchart-js';
import fs from 'fs';
import path from 'path';
import moment from "moment";

export const GET: RequestHandler = async ({ params, fetch,  locals: { supabase, safeGetSession } }) => {
    const session = await safeGetSession();

    if (!session?.user) {
        throw redirect(303, '/auth/unauthorized');
    }

    const devEui = params.dev_eui;

    if (!devEui) {
        throw error(400, 'dev_eui is required');
    }

    const response = await fetch(
        `/api/v1/devices/${params.dev_eui}/data?firstDataDate=${moment().startOf('month').toISOString()}&lastDataDate=${moment().endOf('month').toISOString()}&timezone=asia/tokyo`
    );

    if (!response.ok) {
        throw error(500, 'Unable to get data');
    }

    const data = await response.json();
    const array = data.data.map(d => {
        return [new Date(d.created_at).toISOString(), d.temperatureC.toString(), '']
    })

    // Define your chart data
    const labels = ['January', 'February', 'March', 'April', 'May', 'June'];
    const dataValues = [3, 2, 1, 5, 6, 4];

    // Create a new QuickChart instance
    const qc = new QuickChart();
    qc.setConfig({
        type: 'line',
        data: {
            labels: labels,
            datasets: [{
                label: 'Temperature',
                data: dataValues,
                borderColor: 'rgba(75, 192, 192, 1)',
                backgroundColor: 'rgba(75, 192, 192, 0.2)',
                fill: true,
            }]
        },
        options: {
            scales: {
                y: {
                    beginAtZero: true
                }
            }
        }
    });
    qc.setWidth(800);
    qc.setHeight(600);
    qc.setBackgroundColor('white');

    // Get the chart image URL
    const chartUrl = qc.getUrl();

    // Fetch the image and convert it to base64
    const imageResponse = await fetch(chartUrl);
    const imageBuffer = await imageResponse.arrayBuffer();
    const imageBase64 = Buffer.from(imageBuffer).toString('base64');
    const chartDataUrl = `data:image/png;base64,${imageBase64}`;

    const fontPath = path.join(process.cwd(), './', 'fonts/NotoSansJP/', 'NotoSansJP-Regular.ttf');
    const NotoSansJPRegularFont = fs.readFileSync(fontPath);


    // Prepare data for the report
    const reportDetails = [
        ['会社：', '株式会社TKエビス'],
        ['部署：', 'ペットフード事業部'],
        ['使用場所：', 'xyz'],
        ['センサー名：', 'ABC'],
        ['測定期間', '24/09/01 9:30am - 20/09/30 9:00pm'],
        ['DevEUI', devEui]
    ];

    const sensorDetails = [
        ['サンプリング数', '334'],
        ['Normal: <= -18', '35/334 (0.10%)'],
        ['Notice: >= -18.1', '35/334 (0.10%)'],
        ['Warning: >= -15.1', '35/334 (0.10%)'],
        ['Alert: >= 0', '35/334 (0.10%)'],
        ['最大値', '10℃'],
        ['最小値', '-24℃'],
        ['平均値', '-18℃'],
        ['標準偏差', '15.13℃']
    ];

    // Define fonts using the embedded fonts from pdfMake
    const fonts = {
        Roboto: {
            normal: Buffer.from(pdfFonts.pdfMake.vfs['Roboto-Regular.ttf'], 'base64'),
            bold: Buffer.from(pdfFonts.pdfMake.vfs['Roboto-Medium.ttf'], 'base64'),
            italics: Buffer.from(pdfFonts.pdfMake.vfs['Roboto-Italic.ttf'], 'base64'),
            bolditalics: Buffer.from(pdfFonts.pdfMake.vfs['Roboto-MediumItalic.ttf'], 'base64'),
        },
        NotoSansJP: {
            normal: NotoSansJPRegularFont,
            bold: NotoSansJPRegularFont,
            italics: NotoSansJPRegularFont,
            bolditalics: NotoSansJPRegularFont,
        },
    };

    // Create a new PdfPrinter instance
    const printer = new PdfPrinter(fonts);

    // Define the PDF document
    // Page Margins: [left, top, right, bottom]
    const docDefinition = {
        language: 'ja-jp',
        compress: true,
        pageSize: 'A4',
        pageOrientation: 'portrate',
        pageMargins: [40, 0, 0, 0],
        info: {
            title: 'Refridgerator Report',
            author: 'CropWatch Backend Server',
            subject: 'Cold-Storage',
            keywords: 'Refer Cold Storage',
            creationDate: new Date(),
        },
        // userPassword: '123',
        // ownerPassword: '123456',
        // watermark: { text: `Generated by CropWatch ${new Date()}`, opacity: 0.1, angle: 70 },
        content: [
            {
                text: '週次 温度データレポート',
                style: 'title',
                alignment: 'center',
                margin: [0, 0, 0, 20]
            },
            {
                columns: [
                    // Left column (report-details)
                    {
                        width: '50%',
                        stack: [
                            // Report Details Table
                            {
                                style: 'table',
                                table: {
                                    widths: ['auto', '*'],
                                    body: reportDetails
                                },
                                layout: 'noBorders',
                            },
                            // Horizontal line
                            // { canvas: [{ type: 'line', x1: 0, y1: 0, x2: 275, y2: 0, lineWidth: 1 }], margin: [0, 10, 0, 10] },
                            // Sensor Details Table
                            {
                                style: 'sensorTable',
                                table: {
                                    widths: ['*', '*'],
                                    body: sensorDetails
                                },
                                layout: 'lightHorizontalLines',
                            }
                        ]
                    },
                    // Right column (name-section)
                    {
                        width: '35%',
                        stack: [
                            // Date box
                            {
                                table: {
                                    widths: ['*'],
                                    body: [
                                        [{ text: '日付:', alignment: 'left', margin: [5, 5, 5, 5] }]
                                    ]
                                },
                                layout: {
                                    defaultBorder: true,
                                    hLineWidth: () => 1,
                                    vLineWidth: () => 1,
                                },
                                margin: [0, 0, 0, 10]
                            },
                            // Name boxes
                            {
                                columns: [
                                    {
                                        width: '33%',
                                        table: {
                                            widths: ['*'],
                                            body: [
                                                [{ text: '承認', alignment: 'center', border: [true, true, true, false], margin: [0, 5, 0, 5] }],
                                                [{ text: '', border: [true, false, true, true], margin: [0, 20, 0, 20] }]
                                            ]
                                        },
                                        layout: {
                                            defaultBorder: false,
                                            hLineWidth: () => 1,
                                            vLineWidth: () => 1,
                                            hLineColor: () => '#000',
                                            vLineColor: () => '#000',
                                        }
                                    },
                                    {
                                        width: '33%',
                                        table: {
                                            widths: ['*'],
                                            body: [
                                                [{ text: '確認', alignment: 'center', border: [true, true, true, false], margin: [0, 5, 0, 5] }],
                                                [{ text: '', border: [true, false, true, true], margin: [0, 20, 0, 20] }]
                                            ]
                                        },
                                        layout: {
                                            defaultBorder: false,
                                            hLineWidth: () => 1,
                                            vLineWidth: () => 1,
                                            hLineColor: () => '#000',
                                            vLineColor: () => '#000',
                                        }
                                    },
                                    {
                                        width: '34%',
                                        table: {
                                            widths: ['*'],
                                            body: [
                                                [{ text: '作成', alignment: 'center', border: [true, true, true, false], margin: [0, 5, 0, 5] }],
                                                [{ text: '', border: [true, false, true, true], margin: [0, 20, 0, 20] }]
                                            ]
                                        },
                                        layout: {
                                            defaultBorder: false,
                                            hLineWidth: () => 1,
                                            vLineWidth: () => 1,
                                            hLineColor: () => '#000',
                                            vLineColor: () => '#000',
                                        }
                                    }
                                ],
                                columnGap: 2,
                                margin: [0, 0, 0, 10]
                            },
                            // Comment line
                            { text: 'コメント:', margin: [0, 15, 0, 0] }
                        ],
                        margin: [20, 0, 0, 0]
                    }
                ],
                columnGap: 20,
                margin: [0, 0, 0, 20]
            },
            // Chart image
            {
                id: 'chart',
                image: chartDataUrl,
                width: 595, // Dynamically adjust width or set to 100%
                fit: [595, 400], // Allow the image to scale within these dimensions
                margin: [0, 0, 0, 0],
            },
            // Legend
            // {
            //     id: 'dataPointsLegend',
            //     columns: [
            //         { text: 'Normal: <= -18', fillColor: 'white', border: [true, true, true, true], margin: [0, 0, 0, 0], alignment: 'left' },
            //         { text: 'Notice: >= -18.1 黄色', fillColor: 'yellow', border: [true, true, true, true], alignment: 'center' },
            //         { text: 'Warning: >= -15.1 オレンジ', fillColor: 'orange', border: [true, true, true, true], alignment: 'center' },
            //         { text: 'Alert: >= 0 赤', fillColor: 'red', border: [true, true, true, true], alignment: 'right' }
            //     ],
            //     columnGap: 5,
            //     margin: [0, 10, 0, 0]
            // },
            {
                layout: 'lightHorizontalLines', // optional
                style: 'dataTableLegend',
                table: {
                    // headers are automatically repeated if the table spans over multiple pages
                    // you can declare how many rows should be treated as headers
                    headerRows: 1,
                    widths: ['*', 'auto', 'auto', '*'],

                    body: [
                        ['', '', '', ''],
                        [
                            [{ text: 'Normal: <= -18' }],
                            [{ text: 'Notice: >= -18.1 黄色', fillColor: 'yellow' }],
                            [{ text: 'Warning: >= -15.1 オレンジ', fillColor: 'orange' }],
                            [{ text: 'Alert: >= 0 赤', fillColor: 'red' }],
                        ],
                    ]
                }
            },
            {
                layout: 'lightHorizontalLines', // optional
                style: 'dataTable',
                table: {
                    // headers are automatically repeated if the table spans over multiple pages
                    // you can declare how many rows should be treated as headers
                    headerRows: 1,
                    widths: ['*', 'auto', 'auto', '*'],
                    margin: [40, 0, 0, 0],

                    body: [
                        ['測定日時', '温度', 'コメント'],
                        ...array
                    ]
                }
            }
        ],
        styles: {
            title: {
                fontSize: 18,
                bold: true
            },
            text: {
                fontSize: 10,
            },
            table: {
                margin: [0, 0, 0, 10],
                fontSize: 10,
            },
            sensorTable: {
                margin: [0, 0, 0, 0],
                fontSize: 10,
            },
            dataTable: {
                fontSize: 6,
            },
            dataPointsLegend: {
                fontSize: 10,
            },
            tableHeader: {
                bold: true,
                fontSize: 13,
                color: 'black',
            }
        },
        defaultStyle: { font: 'NotoSansJP' },
        pageBreakBefore: function (currentNode, followingNodesOnPage, nodesOnNextPage, previousNodesOnPage) {
            //check if signature part is completely on the last page, add pagebreak if not
            if (currentNode.id === 'dataTableLegend') {
                return true;
            }
            return false;
        },
    };

    // Generate the PDF document
    const pdfDoc = printer.createPdfKitDocument(docDefinition);

    // Collect the PDF data chunks
    const chunks: Uint8Array[] = [];

    return new Promise<Response>((resolve, reject) => {
        pdfDoc.on('data', (chunk) => chunks.push(chunk));

        pdfDoc.on('end', () => {
            const pdfBuffer = Buffer.concat(chunks);
            resolve(new Response(pdfBuffer, {
                headers: {
                    'Content-Type': 'application/pdf',
                    'Content-Disposition': `attachment; filename="report_${devEui}.pdf"`
                }
            }));
        });

        pdfDoc.on('error', (err) => {
            console.error('PDF generation error:', err);
            reject(error(500, 'Error generating PDF'));
        });

        pdfDoc.end();
    });
};
