<script lang="ts">
	import Calendar from '@event-calendar/core';

	// Initialize your calendar (ensure this matches your actual setup)
	const calendar = new Calendar(document.getElementById('calendar'), {
		view: 'month' // Start with the month view; you can make this dynamic as needed
	});

	// Function to fetch weather data
	async function fetchWeatherData() {
		const response = await fetch(
			'https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.41&hourly=temperature_2m,relative_humidity_2m,rain,cloud_cover&past_days=31'
		);
		const data = await response.json();
		return data;
	}

	// Function to process and display weather data on the calendar
	async function displayWeatherOnCalendar() {
		const weatherData = await fetchWeatherData();

		// Here, you would process the weatherData to match it with calendar dates
		// This might involve iterating over the weather data, extracting the relevant
		// information for each day, and then finding the corresponding day element
		// in the calendar to update it with the weather info.

		// Example of processing (simplified and needs to be adapted):
		weatherData.hourly.time.forEach((time, index) => {
			const date = new Date(time).toDateString(); // Simplified, consider time zones and formatting
			const temperature = weatherData.hourly.temperature_2m[index];
			// More processing as needed

			// Find the calendar day element and update it
			// This is highly dependent on how your calendar HTML is structured
			// You might need to use `document.querySelector` or similar to find the correct day cell
			// Then, update that cell with the weather information
			// For example:
			// let dayCell = document.querySelector(`.calendar-day[data-date="${date}"]`);
			// if(dayCell) {
			//     dayCell.innerHTML += `<div>Temp: ${temperature}°C</div>`; // Simplify and style as needed
			// }
		});
	}

	// Call the function to display weather on the calendar
	displayWeatherOnCalendar();
</script>

<div id="calendar" class="calendar">
	<!-- Days will be generated by JavaScript -->
</div>
